#!/bin/bash
FILES="NewAIs/*"
BROKEN="BROKEN"
for x in $FILES
do
if [ $x != "/var/www/html/NewAIs/*" ];
then
OUTPUT="$(python checkLegal.py $x)"
if [ $OUTPUT != $BROKEN ];
then
if [ -f $OUTPUT/$OUTPUT.go ];
then
rm $OUTPUT/$OUTPUT.go
fi
rm -R TEST
mkdir TEST
cp $x TEST
cp tester.go TEST
cp one/one.go TEST
cd TEST
go build
./TEST
cd ..
if [ -f TEST/complete.txt ];
then
cp $x $OUTPUT
fi
rm $x
fi
fi
done
